server:
  port: 8080
netty:
  port: 9090


spring:
  application:
    name: cyyaw-config
  jpa: #数据库配置
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://34.92.208.10:3306/config?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: because
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:    ################## 上传文件
      max-file-size: 10MB
      max-request-size: 10MB


shiro:
  hashAlgorithmName: md5
  hashIterations: 24


web:
  resources:
    photo:
      uploadPath: /etc/nginx/html/file
      BaseUrl: http://file.dishijiaoyu.com

